layout_spectrum: 0.5696873
typography_spectrum: 0.7639967
color:
  saturation: 0.263579
  lightness: 0.461302
  brandStrength: 0.9073657
  rhythmicContrast: 0.4057274
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Altnative
